version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: node
    restart: unless-stopped
    ports:
      - "3003:8000"
      - "9229:9229"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon --inspect=0.0.0.0:9229 src/server.js
networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
